### ISSUE TITLE
Func:  Partner Table  data fetch and display 

### ISSUE THREAD

**Issue by Net-Set** [Net-Set/Ronx#9]
show partner current user data partner list in table that related table in details show like that id ,walletaddress  and etc...//:
### ronx contract 
`0x6f4dc25CEb0581eDD1Cc5A982794AC021bFEa2a5`
### getdirectpartnerdetails 
`0x5851AB785371DEaD6B9C54114C39a09Cd8F68045`

![image](https://github.com/user-attachments/assets/7c06bd87-637a-40a8-9886-f840affb610f)

**Comment by rajveer9720** [comment]
Resolved 
![image](https://github.com/user-attachments/assets/d3aa13a0-8b21-49af-8efa-03788db8a200)
